# 硬件配置文件
hardware:
  # 硬件配置列表
  left_arm:
      robot_type: "dual_arm_with_pgc"
      interface: can1
      motors: [1, 2, 3, 4, 5, 6]    # 电机ID列表
      joint_names: ["left_joint1", "left_joint2", "left_joint3", "left_joint4", "left_joint5", "left_joint6"]
      frame_id: "left_base_link"
      controller_name: "left_arm_controller"  # 对应的控制器名称
      planning_group: "left_arm"         # MoveIt规划组名称
      initial_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 初始位置
      start_position: [0.0, -0.5236, -0.7854, 0.0, 0.5236, 0.0]  # 启动位置

  right_arm:
      robot_type: "dual_arm_with_pgc"
      interface: can0
      motors: [1, 2, 3, 4, 5, 6]    # 电机ID列表
      joint_names: ["right_joint1", "right_joint2", "right_joint3", "right_joint4", "right_joint5", "right_joint6"]
      frame_id: "right_base_link"
      controller_name: "right_arm_controller"  # 对应的控制器名称
      planning_group: "right_arm"         # MoveIt规划组名称
      initial_position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # 初始位置
      start_position: [0.0, 0.5236, 0.7854, 0.0, -0.5236, 0.0]  # 启动位置

  left_gripper:
      robot_type: "dual_arm_with_pgc"
      interface: can1
      motors: []    # 无电机反馈
      # 仅维护主动关节，finger2 由 URDF mimic 自动联动
      joint_names: ["left_gripper_finger1_joint"]
      frame_id: "left_gripper_base"
      controller_name: "left_gripper_controller"  # 对应的控制器名称
      planning_group: "left_gripper"         # MoveIt规划组名称
      initial_position: [0.0]  # 主动关节初始位置
      start_position: [0.0]  # 启动位置
