chassis_controller_node:
    ros__parameters:
        chassis_type: omnidirectional
        input_topic: cmd_vel
        output_topic: cmd_vel
        joint_command_topic: chassis_joint_commands
        publish_twist: false
        publish_joint_commands: true
        warn_on_unsupported_lateral: true
        wheel_radius: 0.075
        track_width: 0.40
        wheel_base: 0.40
        module_names:
            - front_left
            - front_right
            - rear_left
            - rear_right
        steering_joints:
            - ""
            - ""
            - ""
            - ""
        wheel_joints:
            - front_left_wheel_joint
            - front_right_wheel_joint
            - rear_left_wheel_joint
            - rear_right_wheel_joint
        module_x:
            - 0.20
            - 0.20
            - -0.20
            - -0.20
        module_y:
            - 0.20
            - -0.20
            - 0.20
            - -0.20
        drive_direction_x:
            - 0.7071067811865476
            - 0.7071067811865476
            - 0.7071067811865476
            - 0.7071067811865476
        drive_direction_y:
            - -0.7071067811865476
            - 0.7071067811865476
            - 0.7071067811865476
            - -0.7071067811865476
        steering_axis_sign:
            - 1.0
            - 1.0
            - 1.0
            - 1.0
        wheel_axis_sign:
            - 1.0
            - 1.0
            - 1.0
            - 1.0
